#include "gcode_writer.h"
#include <cmath>
#include <iomanip>

GCodeWriter::GCodeWriter(const std::string& path, const SlicerConfig& cfg) : cfg_(cfg) {
    file_.open(path);
    file_ << std::fixed << std::setprecision(3);
}

GCodeWriter::~GCodeWriter() {
    if (file_.is_open()) file_.close();
}

void GCodeWriter::writeStartGCode() {
    file_ << "; Generated by MyPrinter — Ender 3 V1 / Klipper\n"
          << "M104 S" << (int)cfg_.nozzleTemp << "\n"
          << "M140 S" << (int)cfg_.bedTemp << "\n"
          << "M109 S" << (int)cfg_.nozzleTemp << "\n"
          << "M190 S" << (int)cfg_.bedTemp << "\n"
          << "G28\n"
          << "G1 Z5 F3000\n"
          << "G1 X0 Y0 F3000\n"
          << "G1 Z0.3 F300\n"
          << "G1 X60 E9 F1000\n"
          << "G1 X100 E12.5 F1000\n"
          << "G92 E0\n"
          << "G1 Z2 F3000\n";
    ce_ = 0; retracted_ = true;
}

void GCodeWriter::writeEndGCode() {
    retract();
    file_ << "G91\nG1 Z10 F3000\nG90\n"
          << "G1 X0 Y" << (int)cfg_.buildY << " F3000\n"
          << "M104 S0\nM140 S0\nM84\n";
}

float GCodeWriter::calcE(float dist) {
    float fa = PI * (cfg_.filamentDiam / 2.0f) * (cfg_.filamentDiam / 2.0f);
    return dist * cfg_.layerHeight * cfg_.nozzleDiameter / fa;
}

void GCodeWriter::retract() {
    if (retracted_) return;
    ce_ -= cfg_.retractLength;
    file_ << "G1 E" << ce_ << " F" << (int)(cfg_.retractSpeed * 60) << "\n";
    retracted_ = true;
}

void GCodeWriter::prime() {
    if (!retracted_) return;
    ce_ += cfg_.retractLength;
    file_ << "G1 E" << ce_ << " F" << (int)(cfg_.retractSpeed * 60) << "\n";
    retracted_ = false;
}

void GCodeWriter::travel(float x, float y) {
    retract();
    file_ << "G0 X" << x << " Y" << y << " F" << (int)(cfg_.travelSpeed * 60) << "\n";
    cx_ = x; cy_ = y;
}

void GCodeWriter::extrude(float x, float y, float speed) {
    prime();
    float dx = x - cx_, dy = y - cy_;
    float dist = std::sqrt(dx*dx + dy*dy);
    if (dist < 0.001f) return;
    ce_ += calcE(dist);
    file_ << "G1 X" << x << " Y" << y << " E" << ce_ << " F" << (int)(speed * 60) << "\n";
    cx_ = x; cy_ = y;
}

void GCodeWriter::writeLayer(int layerNum, float z,
                              const std::vector<std::vector<Vec2>>& contours,
                              const std::vector<std::vector<Vec2>>& infill,
                              bool firstLayer) {
    float speed = firstLayer ? cfg_.firstLayerSpeed : cfg_.printSpeed;

    file_ << "\n;LAYER:" << layerNum << "\n";
    file_ << "G0 Z" << z << " F" << (int)(cfg_.travelSpeed * 60) << "\n";
    cz_ = z;

    for (const auto& c : contours) {
        if (c.size() < 3) continue;
        travel(c[0].x, c[0].y);
        for (size_t i = 1; i < c.size(); i++) extrude(c[i].x, c[i].y, speed);
        extrude(c[0].x, c[0].y, speed);
    }

    float infillSpeed = speed * 1.2f;
    for (const auto& line : infill) {
        if (line.size() < 2) continue;
        travel(line[0].x, line[0].y);
        for (size_t i = 1; i < line.size(); i++) extrude(line[i].x, line[i].y, infillSpeed);
    }
}
